"""Pydantic models for request/response schemas."""

from app.models.dishes import (
    CourseType,
    DishBase,
    DishCreate,
    DishIngredientResponse,
    DishListResponse,
    DishResponse,
    DishSummary,
    DishUpdate,
)
from app.models.ingredients import (
    DishIngredientInput,
    IngredientBase,
    IngredientCreate,
    IngredientInstanceBase,
    IngredientInstanceCreate,
    IngredientInstanceResponse,
    IngredientInstanceUpdate,
    IngredientResponse,
    IngredientUpdate,
    ParsedIngredientItem,
    ParsedIngredientList,
    ParseIngredientsRequest,
    ParseIngredientsResponse,
)
from app.models.recipes import (
    DishIngredients,
    ProcessRecipesRequest,
    ProcessRecipesResponse,
    RecipeConfig,
    RecipeInput,
)
from app.models.shopping import (
    ConsolidatedItem,
    DataDefaults,
    ShoppingItem,
    ShoppingListItemCreate,
    ShoppingListItemResponse,
    ShoppingListItemsResponse,
    ShoppingListItemUpdate,
    ShoppingListRequest,
    ShoppingListResponse,
    ValidationWarning,
)
from app.models.stores import (
    StoreBase,
    StoreCreate,
    StoreListResponse,
    StoreResponse,
    StoreUpdate,
)
from app.models.users import (
    PlusOneCreate,
    RSVPListResponse,
    RSVPResponse,
    UserBase,
    UserCreate,
    UserPublicResponse,
    UserResponse,
    UserUpdate,
)

__all__ = [
    # Dishes
    "CourseType",
    "DishBase",
    "DishCreate",
    "DishIngredientResponse",
    "DishListResponse",
    "DishResponse",
    "DishSummary",
    "DishUpdate",
    # Ingredients
    "DishIngredientInput",
    "IngredientBase",
    "IngredientCreate",
    "IngredientInstanceBase",
    "IngredientInstanceCreate",
    "IngredientInstanceResponse",
    "IngredientInstanceUpdate",
    "IngredientResponse",
    "IngredientUpdate",
    "ParsedIngredientItem",
    "ParsedIngredientList",
    "ParseIngredientsRequest",
    "ParseIngredientsResponse",
    # Recipes
    "DishIngredients",
    "ProcessRecipesRequest",
    "ProcessRecipesResponse",
    "RecipeConfig",
    "RecipeInput",
    # Shopping
    "ConsolidatedItem",
    "DataDefaults",
    "ShoppingItem",
    "ShoppingListItemCreate",
    "ShoppingListItemResponse",
    "ShoppingListItemsResponse",
    "ShoppingListItemUpdate",
    "ShoppingListRequest",
    "ShoppingListResponse",
    "ValidationWarning",
    # Stores
    "StoreBase",
    "StoreCreate",
    "StoreListResponse",
    "StoreResponse",
    "StoreUpdate",
    # Users
    "PlusOneCreate",
    "RSVPListResponse",
    "RSVPResponse",
    "UserBase",
    "UserCreate",
    "UserPublicResponse",
    "UserResponse",
    "UserUpdate",
]
